dist: trusty
language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
before_script:
- npm install -g httpserver
- cd dist && httpserver -p 8080 &
script:
- npm start
- npx cypress run
deploy:
  provider: surge
  skip_cleanup: true
  domain: honorable-direction.surge.sh
  project: ./dist
  on:
    branch: master
