dist: trusty
language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
script:
- npm start
- npx cypress run
deploy:
  provider: surge
  skip_cleanup: true
  domain: honorable-direction.surge.sh
  project: ./dist
  on:
    branch: master
